### ISSUE TITLE
 Why the prediction of the model I trained is not accurate, is it because the label format I fed is not correct?

### ISSUE THREAD

**Issue by qianbeidexiaoyu** [puruBHU/YOLSE_keras#2]
CushahuanDormitory_Single_Seven_color_501.jpg | 0.284375 | 0.283333 | 0.654688 | 0.839583 | 0.370313 | 0.808333 | 0.303125 | 0.49375 | 0 | 0 | 0 | 0 | 0.45 | 0.302083
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

This is the label format I used 
0 means no fingertip coordinates
The predicted five finger positions are all at (63,63)
Can I use the model you trained？

**Comment by puruBHU** [comment]
In the label format that you have provided above, I assume that the first four values are bounding box coordinates of the hand. 

Also, you are training your model on the extracted hand image.

To train the model, first of all, you need to rescale all the fingertips coordinates according to the extracted hand image using the bounding box coordinates.

After you have made the prediction you need to rescale back the obtained coordinates to the original image size.

Let me know if this helps.

**Comment by qianbeidexiaoyu** [comment]
OK!I guess it should be that my fingertip coordinates are not rescaled.
thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Purnendu Mishra"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午3:28
收件人:&nbsp;"puruBHU/YOLSE_keras"<YOLSE_keras@noreply.github.com&gt;;
抄送:&nbsp;"347780288"<347780288@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [puruBHU/YOLSE_keras]  Why the prediction of the model I trained is not accurate, is it because the label format I fed is not correct? (#2)





 
In the label format that you have provided above, I assume that the first four values are bounding box coordinates of the hand.
 
Also, you are training your model on the extracted hand image.
 
To train the model, first of all, you need to rescale all the fingertips coordinates according to the extracted hand image using the bounding box coordinates.
 
After you have made the prediction you need to rescale back the obtained coordinates to the original image size.
 
Let me know if this helps.

**Comment by qianbeidexiaoyu** [comment]
Hello,&nbsp;I am a student of Shenzhen University of Technology.Thank you very much for your help last time, it helped me a lot.
Since the last successful code modification, I successfully ran your code and got the trained model.
But its prediction result is not accurate. I know that I must have made a mistake, but I have not found the reason.
Its y_pred(hearmap) always has higher weight on the four edges：Just&nbsp;like the two pictures below.
&nbsp;&nbsp;
Although I checked (batch_x, batch_y), I think its input should be correct, and the network structure should be ok, so I don’t know where the problem is.
I also attached the code, if there is time, can you help me to look at it, thank you very&nbsp;very much.

**Comment by puruBHU** [comment]
I cannot find any attachments.

The code is the implementation of the methodology given in the paper
**YOLSE: Egocentric Fingertip Detection from Single RGB Images**

Follow this paper.

**Comment by qianbeidexiaoyu** [comment]
It may not be visible on github. Can you send me a normal email address&nbsp;or other contact information?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Purnendu Mishra"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 晚上10:27
收件人:&nbsp;"puruBHU/YOLSE_keras"<YOLSE_keras@noreply.github.com&gt;;
抄送:&nbsp;"347780288"<347780288@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [puruBHU/YOLSE_keras]  Why the prediction of the model I trained is not accurate, is it because the label format I fed is not correct? (#2)





 
I cannot find any attachments.
 
The code is the implementation of the methodology given in the paper
 YOLSE: Egocentric Fingertip Detection from Single RGB Images
 
Follow this paper.

**Comment by puruBHU** [comment]
my mail id is purnendu06@gmail.com

**Comment by puruBHU** [comment]
It is difficult to tell why you are getting different output than your desired value. Try to visualize the target heatmap and verify whether they are correct or not. If the target is not correct then the model will not train properly.

**Comment by qianbeidexiaoyu** [comment]
Ok thanks&nbsp;
I will debug it carefully.
If there are other problems, I will consult you in detail.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Purnendu Mishra"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 下午3:03
收件人:&nbsp;"puruBHU/YOLSE_keras"<YOLSE_keras@noreply.github.com&gt;;
抄送:&nbsp;"347780288"<347780288@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [puruBHU/YOLSE_keras]  Why the prediction of the model I trained is not accurate, is it because the label format I fed is not correct? (#2)





 
It is difficult to tell why you are getting different output than your desired value. Try to visualize the target heatmap and verify whether they are correct or not. If the target is not correct then the model will not train properly.
